### ISSUE TITLE
Is ISO_Fortran_binding.h installed properly?

### ISSUE THREAD

**Issue by aradi** [conda-forge/gfortran_impl_osx-64-feedstock#78]
### Comment:

As I have no access to Mac hardware, I can not check myself. But it seems to me, that the missing `ISO_Fortran_binding.h` issue for the gfortran compilers, which was fixed in conda-forge/ctng-compilers-feedstock#123 for Linux, is still available on osx_64. At least, the building of MPICH with modern Fortran interfaces, which requires this include file, seems to be successful now on all platforms, except osx_64, where the compiler capability detection fails due to the missing include file (conda-forge/mpich-feedstock#84).

Could you please, check, whether the osx_64 Conda package contains that include file, and make a similar fix to conda-forge/ctng-compilers-feedstock#123, if not? (@isuruf as you fixed the other package, could you give this a look?)

**Comment by dalcinl** [comment]
@aradi I just checked on an Intel Mac, and the header seems to be installed, at least for gfortran=11,12,13. Of course, I just tested with `conda create -n ftn gfortran=X`. Am I missing something?

**Comment by aradi** [comment]
@dalcinl Thanks for checking it. The reason, why I thought the file could be missing, is that my PR for the F2008 support in MPICH (conda-forge/mpich-feedstock#84) works fine for all platforms, except for osx_64. Apparently, the MPICH configure script can not detect the F2008 support of the compiler (`2024-01-28T16:03:42.0027680Z checking for Fortran 2008 support... no`). I had the same problem with the Linux compilers before, which I could then track down to the missing `ISO_Fortran_binding.h` in the compiler packages. Once this had been fixed in conda-forge/ctng-compilers-feedstock#123, the MPICH configure script worked correctly with those compilers.

But then, I am wondering, why the MPICH configure script does not detect Fortran 2008 on osx_64...

**Comment by aradi** [comment]
OK, since the file is apparently installed, I'll close this question.
